language: python
python:
  - "3.6"

# command to install dependencies
# nothing
install:

# 只在更新 develop 时执行
branches:
  only:
    - master 

# 执行清缓存，生成网页操作
script:
  - git config user.name "DCMMC"
  - git config user.email "xwt97294597@gmail.com"
  - git clone --branch=develop --depth=1 https://github.com/DCMMC/DCMMC.github.io /tmp/DCMMC.github.io && cd /tmp/DCMMC.github.io && git submodule init && git submodule update && git remote rm origin && git remote add origin https://DCMMC:${Github_TOKEN}@github.com/DCMMC/DCMMC.github.io && cd ./source/_posts && git pull origin master && cd ../.. && git add -A . && git add -A ./source/_posts && git commit -m 'update _posts by Travis-CI' && git push origin develop
